### ISSUE TITLE
Upload tar.gz Bokeh package is failing

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Server/anaconda-client#230]
In a recent build, I found this issue:

```python
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 82, in main
    description=__doc__, version=version)
  File "/home/travis/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 64, in binstar_main
    return args.main(args)
  File "/home/travis/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 170, in main
    filename, parser_args=args)
  File "/home/travis/miniconda/lib/python2.7/site-packages/binstar_client/utils/detect.py", line 96, in get_attrs
    return detectors[package_type](filename, fileobj, *args, **kwargs)
TypeError: inspect_pypi_package() got an unexpected keyword argument 'parser_args'
```

I think this is the offending commit: https://github.com/Anaconda-Server/anaconda-client/commit/b1ac44438cb54126125be675de04400c0b3bcd2e

ping @malev, ideas?

**Comment by malev** [comment]
is this happening only in `1.1.2` ?

**Comment by damianavila** [comment]
Not sure... previous successful experience was with 1.0.2...

**Comment by dalcinl** [comment]
I could upload by downgrading to ``1.0.2``. Both ``1.1.0`` and ``1.1.2`` failed with the same error.
